version: 2
updates:
  # Maintain dependencies for release-automation
  - package-ecosystem: "gomod"
    directory: "/release-automation"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"

# Maintain dependencies for release-notifier
  - package-ecosystem: "gomod"
    directory: "/release-notifier"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"