blank_issues_enabled: false
contact_links:
  - name: Eclipse Tractus X Community Overview
    url: https://eclipse-tractusx.github.io/community
    about: If you need an Overview of all Eclipse Tractus X community products
